language: php
php:
  - 7.1
  - 7.2
  - 7.3

services:
  - postgresql
  
addons:
    postgresql: "9.6"

install:
  - composer require php-coveralls/php-coveralls

before_script:
  - createuser -U postgres root
  - createdb -U postgres -O root tokeneditor
  - psql -f db_schema.sql tokeneditor
  - mkdir -p build/logs

after_success:
  - php vendor/bin/php-coveralls -v

